/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1a0c.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1a0e.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1a17.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1a2z.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1a5z.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1a95.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1ao0.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1auv.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1ax4.pdb -z -e D2 -o aligned/
/Applications/MacPyMOL.app/Contents/MacOS/MacPyMOL -ck ~/crystal_pymolscripts/auto_prep/auto_prep_dihedral_pdb_4.py -- -i 1b65.pdb -z -e D2 -o aligned/
